### ISSUE TITLE
A couple of small issues.

### ISSUE THREAD

**Issue by filmio** [pibby/loruki#1]
Very nice job with this portfolio piece. I noticed when viewing the site in Safari that the addition of height:100% for images is giving you a less than ideal display. All stretchy vertically. No issues on Chrome or FF. I have attached an image to illustrate.

The other thing that stood out to me is that the distance the stats line travels has it overlap with the terminal image. It doesn't translate well and feels somewhat broken.

<img width="1267" alt="stretchy" src="https://user-images.githubusercontent.com/24705294/112539688-890a3a80-8d6e-11eb-9a23-9db50586a401.png">

**Comment by pibby** [comment]
Thanks for the feedback, @filmio. I'll take a look at Safari and make some adjustments.
